### ISSUE TITLE
Hi Sir,when I use 1 channel I met this problem

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#19]
I opened the autoplay function.When I watch some movie(like: the long voyage home),it just didnot react.Everything is freezed,whatever key I click the remote.I have to restart kodi.Sir,you can try the movie :the long voyage home.

**Comment by tknorris** [comment]
Need a log.

**Comment by brmnh** [comment]
Hi Sir,this is the log link:http://xbmclogs.com/pbaxeopwy

**Comment by tknorris** [comment]
It looks like there were no usable sources for that movie, so that addon just exitted. Some kind of notification in that case would be nice, but it's not really a bug.

**Comment by brmnh** [comment]
but it seems all keys of remote donot function.

**Comment by brmnh** [comment]
It just freezed in highlight.

**Comment by brmnh** [comment]
if it is just no sources,I can just go back to another movie,but the truth is the go back key of the remote donot work any longer.

**Comment by tknorris** [comment]
Oh, I see what you mean, that sounds like a kodi bug rather than 1CH though because the addon is no longer running after that log line you show.That last line in your log is generated by this line of code: https://github.com/tknorris/1Channel/blob/master/default.py#L336

There's no more code after that...

**Comment by brmnh** [comment]
So Sir,can you fix it?

**Comment by tknorris** [comment]
No, there's nothing for me to fix. I suspect it's an old Kodi bug that happens when 2 dialogs appear at the same time. If you want to fix it for just yourself, you could comment out the line I linked above (put a # in front of the line) and see if it stops kodi from hanging. The point is, I should be able to use that code, and it's a kodi problem that I can't, not an addon problem.

**Comment by brmnh** [comment]
Sir ,it works,the go back key of remote now works.Thanks.

**Comment by tknorris** [comment]
great.
