### ISSUE TITLE
Hi Sir,the addon SALTS is too slow

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#198]
When I search movies in the SALTS,it reacts too slowly.I can not understand,it is very fast before.Things changed in recent one month.Do you no longer develop the addon?Or it is deveoped by tvaddons?Sir,may you make some fix on the addon.Otherwise the addon has little value left,since the reaction time is too long.

**Comment by brmnh** [comment]
When you search some movie the reaction time is several minutes now,before it only takes a few seconds.It is completely a disaster now.

**Comment by tknorris** [comment]
Man, I don't know what you deal is, but if one function out of 100 takes longer than it used to then the addon is a disaster for you then I'd rather you just use another addon. I have no patience for that kind of attitude for something I work on in my spare time. The searches take longer because image scraping is done differently now which you would know if you took 10 seconds to google. Do better searches with fewer results or turn off images in addon settings.
