### ISSUE TITLE
not issue: wip source for hqq | netu

### ISSUE THREAD

**Issue by smokdpi** [tknorris/script.module.urlresolver#44]
Current wip, seems to be pretty close. Either I'm missing something, or it has something to do with SNI/SSL (Not sure which atm). Just posting it as an issue with a link to the source in case you are interested in taking a shot as well, if you aren't already :) 

https://raw.githubusercontent.com/smokdpi/urlresolver_plugins/master/hqq.py

**Comment by smokdpi** [comment]
Test url's can be found at full-stream

**Comment by tknorris** [comment]
I haven't looked at it in detail yet. But two things I noticed:
1) Consider using the USER_AGENT strings available in urlresolver/common. I added ones for most common browsers so that we can change them centrally.
2) The loI() method is just a custom implementation of base64decode
3) xc13 might be a rot13 implementation, but I didn't test that.

**Comment by smokdpi** [comment]
Made a few changes with it to no avail... the final url seems to be correct from what I could find in wireshark. Though direct access results are; in browser it's SSL overlap/mismatch errors and kodi/curl http error 600

Not sure about the 10l method and if I'm not mistaken rot13 isn't natively available until python3 so I've left those alone for now.

Going to look into wireshark, and the uppod api for any clues to use with |sslcipherlist= next time I have bit

**Comment by smokdpi** [comment]
leaving wip resolver file where it is for now but closing conversation
